import LegalLayout from "@/components/legal/LegalLayout";

export const metadata = { title: "Terms of Service · PumAI" };

export default function TermsPage() {
  return (
    <LegalLayout title="Terms of Service" lastUpdated="20 April 2026">
      <p>
        These Terms of Service (&quot;Terms&quot;) govern your use of the PumAI platform (&quot;Service&quot;). By using the
        Service you agree to these Terms. If you do not agree, do not use the Service.
      </p>

      <h2>1. The Service</h2>
      <p>
        PumAI provides AI-powered conversational agents that integrate with Webchat, WhatsApp, Instagram and Facebook
        Messenger. The Service is operated from Australia.
      </p>

      <h2>2. Account</h2>
      <ul>
        <li>You must be at least 18 years old and authorised to enter into contracts on behalf of your business.</li>
        <li>You are responsible for the security of your credentials.</li>
        <li>You agree to provide accurate and up-to-date information.</li>
      </ul>

      <h2>3. Subscription and billing</h2>
      <ul>
        <li>All prices are in Australian dollars and include GST unless stated otherwise.</li>
        <li>Subscriptions renew automatically every month until cancelled.</li>
        <li>Payments are processed by <strong>Stripe</strong>. We do not store card details.</li>
        <li>Setup fees are charged once on the first invoice. Bundle setup (2+ channels in a single cart) is a flat A$350.</li>
        <li>Add-on channels (after your first paid channel) are A$350/month and run at Growth tier limits.</li>
      </ul>

      <h2>4. Cancellation and refunds</h2>
      <ul>
        <li>You can cancel at any time via the Stripe billing portal.</li>
        <li>Cancellation takes effect at the end of the current billing period.</li>
        <li>We do not provide pro-rata refunds for unused time, except where required by the Australian Consumer Law.</li>
        <li>If the Service fails to comply with consumer guarantees, you may be entitled to a refund, replacement or repair
          under Australian Consumer Law.</li>
      </ul>

      <h2>5. Free tier</h2>
      <p>
        The Free tier includes Webchat only, limited to 10 conversations per calendar month. Free accounts may not connect
        WhatsApp, Instagram or Messenger.
      </p>

      <h2>6. Acceptable use</h2>
      <p>
        Your use of the Service is subject to our <a href="/acceptable-use">Acceptable Use Policy</a>. Breach may result in
        suspension or termination of your account.
      </p>

      <h2>7. AI output</h2>
      <ul>
        <li>Responses generated by the AI are provided &quot;as is&quot;. They may be inaccurate or incomplete.</li>
        <li>You are responsible for reviewing AI output before relying on it for decisions.</li>
        <li>The Service is not a substitute for professional legal, medical, financial or other advice.</li>
      </ul>

      <h2>8. Your content</h2>
      <ul>
        <li>You retain ownership of the messages, knowledge bases and data you submit.</li>
        <li>You grant us a licence to process your content solely to provide the Service.</li>
        <li>You warrant that you have the right to submit any content you upload.</li>
      </ul>

      <h2>9. Third-party platforms</h2>
      <p>
        The Service integrates with Meta (Facebook, Instagram), WhatsApp and other platforms. Your use of those platforms is
        governed by their respective terms and policies. We are not responsible for changes or interruptions caused by those
        platforms.
      </p>

      <h2>10. Service availability</h2>
      <ul>
        <li>We aim to maintain high availability but do not guarantee uninterrupted service on non-Enterprise plans.</li>
        <li>Enterprise plans may include specific uptime commitments as agreed in writing.</li>
      </ul>

      <h2>11. Limitation of liability</h2>
      <p>
        To the extent permitted by law, our total liability arising from or in connection with the Service is limited to the
        amount you have paid in the 12 months preceding the claim. We are not liable for indirect or consequential loss
        (including loss of profits, goodwill or data).
      </p>
      <p>
        Nothing in these Terms excludes or limits rights you have under the Australian Consumer Law that cannot be excluded.
      </p>

      <h2>12. Suspension and termination</h2>
      <ul>
        <li>We may suspend or terminate your account if you breach these Terms or the Acceptable Use Policy.</li>
        <li>We may suspend or terminate accounts with unpaid invoices after 21 days past due.</li>
        <li>On termination you will lose access to the Service. Your data may be retained for a limited period as described
          in our Privacy Policy.</li>
      </ul>

      <h2>13. Changes to the Terms</h2>
      <p>
        We may update these Terms. Material changes will be notified by email or in the dashboard at least 14 days before
        taking effect. Continued use of the Service after that date constitutes acceptance.
      </p>

      <h2>14. Governing law</h2>
      <p>
        These Terms are governed by the laws of New South Wales, Australia. Any dispute will be subject to the exclusive
        jurisdiction of the courts of New South Wales.
      </p>

      <h2>15. Contact</h2>
      <p>
        Legal — <a href="mailto:legal@pumai.com.au">legal@pumai.com.au</a> <br />
        Support — <a href="mailto:support@pumai.com.au">support@pumai.com.au</a>
      </p>
    </LegalLayout>
  );
}
